import api from '../lib/axios';
export const employeesApi = {
  list:           (params)    => api.get('/employees', { params }),
  get:            (id)        => api.get(`/employees/${id}`),
  create:         (data)      => api.post('/employees', data),
  update:         (id, data)  => api.put(`/employees/${id}`, data),
  delete:         (id)        => api.delete(`/employees/${id}`),
  uploadPhoto:    (id, fd)    => api.post(`/employees/${id}/photo`, fd, { headers: { 'Content-Type': 'multipart/form-data' } }),
  assignManager:  (id, manager_id) => api.post(`/employees/${id}/assign-manager`, { manager_id }),
  documents:      (id)        => api.get(`/employees/${id}/documents`),
  uploadDocument: (id, fd)    => api.post(`/employees/${id}/documents`, fd, { headers: { 'Content-Type': 'multipart/form-data' } }),
  allowances:     (id)        => api.get(`/employees/${id}/allowances`),
  departments:          ()           => api.get('/departments'),
  createDepartment:     (data)       => api.post('/departments', data),
  updateDepartment:     (id, data)   => api.put(`/departments/${id}`, data),
  deleteDepartment:     (id)         => api.delete(`/departments/${id}`),
  sites:                (params)     => api.get('/sites', { params }),
  createSite:           (data)       => api.post('/sites', data),
  updateSite:           (id, data)   => api.put(`/sites/${id}`, data),
  deleteSite:           (id)         => api.delete(`/sites/${id}`),
  jobTitles:            ()           => api.get('/job-titles'),
  departmentEmployees:  (id)         => api.get(`/departments/${id}/employees`),
  siteEmployees:        (id)         => api.get(`/sites/${id}/employees`),
  activateSite:         (id)         => api.post(`/sites/${id}/activate`),
  deactivateSite:       (id)         => api.post(`/sites/${id}/deactivate`),
};
