<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Arial, Helvetica, sans-serif; font-size: 11px; color: #1e293b; }
  .page { padding: 28px; }
  .header { display: flex; justify-content: space-between; border-bottom: 3px solid #d97706; padding-bottom: 14px; margin-bottom: 20px; }
  .company-name { font-size: 18px; font-weight: 800; color: #0a0f1e; }
  .company-sub  { font-size: 10px; color: #64748b; margin-top: 2px; }
  .report-badge { background: #d97706; color: #fff; padding: 5px 14px; border-radius: 20px; font-size: 10px; font-weight: 700; text-transform: uppercase; }
  .report-meta  { text-align: right; font-size: 10px; color: #64748b; margin-top: 4px; }
  .summary-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 10px; margin-bottom: 20px; }
  .stat-box { border: 1px solid #e2e8f0; border-radius: 8px; padding: 10px 14px; }
  .stat-label { font-size: 9px; font-weight: 700; text-transform: uppercase; color: #94a3b8; }
  .stat-value { font-size: 16px; font-weight: 800; color: #0a0f1e; margin-top: 3px; }
  .stat-amber { border-top: 3px solid #d97706; }
  .stat-green { border-top: 3px solid #059669; }
  .stat-blue  { border-top: 3px solid #2563eb; }
  h3 { font-size: 11px; font-weight: 700; text-transform: uppercase; border-left: 3px solid #d97706; padding-left: 8px; margin-bottom: 10px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
  thead tr { background: #0a0f1e; color: #e2e8f0; }
  thead th { padding: 8px 10px; text-align: left; font-size: 10px; }
  tbody tr:nth-child(even) { background: #f8fafc; }
  tbody td { padding: 7px 10px; border-bottom: 1px solid #f1f5f9; }
  .r { text-align: right; }
  .total-row td { font-weight: 700; background: #fffbeb; border-top: 2px solid #d97706; }
  .footer { margin-top: 24px; border-top: 1px solid #e2e8f0; padding-top: 10px; display: flex; justify-content: space-between; color: #94a3b8; font-size: 9px; }
</style>
</head>
<body>
<div class="page">
  <div class="header">
    <div>
      <div class="company-name">BERVES ENGINEERING LIMITED</div>
      <div class="company-sub">Human Resource Management System</div>
    </div>
    <div style="text-align:right">
      <div class="report-badge">Overtime Report</div>
      <div class="report-meta">Period: {{ $month }} &nbsp;|&nbsp; Generated: {{ now()->format('d M Y, H:i') }}</div>
    </div>
  </div>

  <div class="summary-grid">
    <div class="stat-box stat-amber">
      <div class="stat-label">Total Records</div>
      <div class="stat-value">{{ $data['total_records'] ?? 0 }}</div>
    </div>
    <div class="stat-box stat-blue">
      <div class="stat-label">Total Hours</div>
      <div class="stat-value">{{ number_format($data['total_hours'] ?? 0, 1) }}h</div>
    </div>
    <div class="stat-box stat-green">
      <div class="stat-label">Total Amount</div>
      <div class="stat-value">GHS {{ number_format($data['total_amount'] ?? 0, 2) }}</div>
    </div>
  </div>

  @if(!empty($data['records']))
  <h3>Overtime Detail</h3>
  <table>
    <thead>
      <tr><th>Employee</th><th>Department</th><th>Date</th><th>Type</th><th class="r">Hours</th><th class="r">Rate×</th><th class="r">Amount (GHS)</th><th>Status</th></tr>
    </thead>
    <tbody>
      @foreach($data['records'] as $rec)
      <tr>
        <td>{{ $rec['employee'] }}</td>
        <td>{{ $rec['department'] }}</td>
        <td>{{ $rec['date'] }}</td>
        <td>{{ ucfirst(str_replace('_',' ', $rec['day_type'])) }}</td>
        <td class="r">{{ $rec['hours'] }}</td>
        <td class="r">{{ $rec['rate_multiplier'] }}×</td>
        <td class="r">{{ number_format($rec['amount'], 2) }}</td>
        <td>{{ $rec['approved_by'] ? 'Approved' : 'Pending' }}</td>
      </tr>
      @endforeach
      <tr class="total-row">
        <td colspan="4">TOTAL</td>
        <td class="r">{{ number_format($data['total_hours'], 1) }}</td>
        <td></td>
        <td class="r">{{ number_format($data['total_amount'], 2) }}</td>
        <td></td>
      </tr>
    </tbody>
  </table>
  @endif

  <div class="footer">
    <span>Berves Engineering Limited — Overtime Report — Confidential</span>
    <span>Generated by HRMS v2.0 &nbsp;|&nbsp; {{ now()->format('d M Y') }}</span>
  </div>
</div>
</body>
</html>
