<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Arial, Helvetica, sans-serif; font-size: 11px; color: #1e293b; }
  .page { padding: 28px; }
  .header { display: flex; justify-content: space-between; border-bottom: 3px solid #2563eb; padding-bottom: 14px; margin-bottom: 20px; }
  .company-name { font-size: 18px; font-weight: 800; color: #0a0f1e; }
  .company-sub  { font-size: 10px; color: #64748b; margin-top: 2px; }
  .report-badge { background: #2563eb; color: #fff; padding: 5px 14px; border-radius: 20px; font-size: 10px; font-weight: 700; text-transform: uppercase; }
  .report-meta  { text-align: right; font-size: 10px; color: #64748b; margin-top: 4px; }
  .summary-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 10px; margin-bottom: 20px; }
  .stat-box { border: 1px solid #e2e8f0; border-radius: 8px; padding: 10px 14px; }
  .stat-label { font-size: 9px; font-weight: 700; text-transform: uppercase; color: #94a3b8; }
  .stat-value { font-size: 16px; font-weight: 800; color: #0a0f1e; margin-top: 3px; }
  .stat-blue  { border-top: 3px solid #2563eb; }
  .stat-green { border-top: 3px solid #059669; }
  .stat-amber { border-top: 3px solid #d97706; }
  h3 { font-size: 11px; font-weight: 700; text-transform: uppercase; border-left: 3px solid #2563eb; padding-left: 8px; margin-bottom: 10px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
  thead tr { background: #0a0f1e; color: #e2e8f0; }
  thead th { padding: 8px 10px; text-align: left; font-size: 10px; }
  tbody tr:nth-child(even) { background: #f8fafc; }
  tbody td { padding: 7px 10px; border-bottom: 1px solid #f1f5f9; }
  .r { text-align: right; }
  .bar-cell { width: 120px; }
  .bar-bg { background: #e2e8f0; border-radius: 4px; height: 8px; width: 100%; }
  .bar-fill { background: #2563eb; border-radius: 4px; height: 8px; }
  .footer { margin-top: 24px; border-top: 1px solid #e2e8f0; padding-top: 10px; display: flex; justify-content: space-between; color: #94a3b8; font-size: 9px; }
</style>
</head>
<body>
<div class="page">
  <div class="header">
    <div>
      <div class="company-name">BERVES ENGINEERING LIMITED</div>
      <div class="company-sub">Human Resource Management System</div>
    </div>
    <div style="text-align:right">
      <div class="report-badge">Attendance Report</div>
      <div class="report-meta">Period: {{ $month }} &nbsp;|&nbsp; Generated: {{ now()->format('d M Y, H:i') }}</div>
    </div>
  </div>

  <div class="summary-grid">
    <div class="stat-box stat-blue">
      <div class="stat-label">Working Days</div>
      <div class="stat-value">{{ $data['working_days'] ?? count($data['trend'] ?? []) }}</div>
    </div>
    <div class="stat-box stat-green">
      <div class="stat-label">Avg Attendance Rate</div>
      <div class="stat-value">{{ number_format($data['avg_rate'] ?? 0, 1) }}%</div>
    </div>
    <div class="stat-box stat-amber">
      <div class="stat-label">Total Late Arrivals</div>
      <div class="stat-value">{{ $data['total_late'] ?? 0 }}</div>
    </div>
  </div>

  @if(!empty($data['trend']))
  <h3>Daily Attendance Trend</h3>
  <table>
    <thead><tr><th>Date</th><th class="r">Present</th><th class="r">Absent</th><th class="r">Late</th><th class="r">Rate %</th></tr></thead>
    <tbody>
      @foreach($data['trend'] as $row)
      <tr>
        <td>{{ $row['date'] }}</td>
        <td class="r">{{ $row['present'] }}</td>
        <td class="r">{{ $row['absent'] ?? 0 }}</td>
        <td class="r">{{ $row['late'] ?? 0 }}</td>
        <td class="r">{{ $row['rate'] }}%</td>
      </tr>
      @endforeach
    </tbody>
  </table>
  @endif

  @if(!empty($data['by_department']))
  <h3>Attendance by Department</h3>
  <table>
    <thead><tr><th>Department</th><th class="r">Total Days</th><th class="r">Present</th><th class="r">Absent</th><th class="r">Rate</th></tr></thead>
    <tbody>
      @foreach($data['by_department'] as $dept)
      <tr>
        <td>{{ $dept['name'] }}</td>
        <td class="r">{{ $dept['total'] ?? 0 }}</td>
        <td class="r">{{ $dept['present'] ?? 0 }}</td>
        <td class="r">{{ $dept['absent'] ?? 0 }}</td>
        <td class="r">{{ $dept['rate'] ?? 0 }}%</td>
      </tr>
      @endforeach
    </tbody>
  </table>
  @endif

  <div class="footer">
    <span>Berves Engineering Limited — Attendance Report — Confidential</span>
    <span>Generated by HRMS v2.0 &nbsp;|&nbsp; {{ now()->format('d M Y') }}</span>
  </div>
</div>
</body>
</html>
